# .streamlit/secrets.toml

[postgresql]
dialect = "postgresql"
host = "localhost"
port = "5432"
database = "youtube"
username = "postgres"
password = "#####"

# .streamlit/secrets.toml

[mongo]
host = "localhost"
port = 27017
username = "xxx"
password = "xxx"

